Region: us-east-1
Image:
  Os: centos7
HeadNode:
  InstanceType: c5.large
  Networking:
    SubnetId: subnet-035d8f31ab1ba21ac
  DisableSimultaneousMultithreading: true
  Ssh:
    KeyName: centos
Scheduling:
  Scheduler: slurm
  SlurmQueues:
    - Name: queue1
      CapacityType: SPOT
      Networking:
        SubnetIds:
          - subnet-035d8f31ab1ba21ac
      ComputeResources:
        - Name: compute-resource-1
          InstanceType: c5.4xlarge
          MinCount: 0
          MaxCount: 10
SharedStorage:
  - MountDir: /shared
    Name: ebs-shared
    StorageType: Ebs
  - MountDir: /fsx
    Name: name2
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
