Region: us-east-1
Image:
  Os: centos7
HeadNode:
  InstanceType: c5.large
  Networking:
    SubnetId: subnet-09dde93abd00c9cae
  DisableSimultaneousMultithreading: true
  Ssh:
    KeyName: centos
  LocalStorage:
    RootVolume:
      Size: 100
      Encrypted: false
      VolumeType: gp2
      Iops: 100
      DeleteOnTermination: true
Scheduling:
  Scheduler: slurm
  SlurmSettings:
    ScaledownIdletime: 10
    Dns:
      DisableManagedDns: true
  SlurmQueues:
    - Name: queue1
      CapacityType: ONDEMAND
      Networking:
        SubnetIds:
          - subnet-09dde93abd00c9cae
      ComputeResources:
        - Name: compute-resource-1
          InstanceType: c5.4xlarge
          MinCount: 0
          MaxCount: 10
SharedStorage:
  - MountDir: /shared
    Name: name1
    StorageType: Ebs
    EbsSettings:
      VolumeType: gp2  # gp2 | gp3 | io1 | io2 | sc1 | st1 | standard
      Size: 100
  - MountDir: /fsx
    Name: name2
    StorageType: FsxLustre
    FsxLustreSettings:
      StorageCapacity: 1200
AdditionalPackages:
  IntelSoftware:
    IntelHpcPlatform: false
