site_name: cmaq_parallel_cluster
nav:
    - Home: 'index.md'
    - User Guide for AWS Parallel Cluster:
        - 'System Requirements AWS': 'user_guide/system-requirements-parallel-cluster.md'
        - 'Demo Cluster': 'user_guide/demo-cluster.md'
        - 'AWS MVP Parallel Cluster': 'user_guide/aws-pcluster-cluster.md'
        - 'Install CMAQ on Pcluster': 'user_guide/software-install-pcluster.md'
        - 'Install Input Data': 'user_guide/input-data-install.md'
        - 'Run CMAQ CONUS Benchmark on Pcluster': 'user_guide/run-cmaq-benchmark-pcluster.md'
        - 'Compare timings': 'user_guide/parse_timing.md'
        - 'QA CMAQ Output': 'user_guide/qa_cmaq_run.md'
        - 'Saving Output': 'user_guide/copy_output_to_S3_Bucket.md'
        - 'Shared Lustre File System & Importing from S3 Bucket': 'user_guide/lustre-import-from-S3-bucket.md'
    - User Guide for Azure Cycle Cloud:
        - 'System Requirements Azure': 'user_guide/system-requirements-cycle-cloud.md'
        - 'Azure CycleCloud Cluster': 'user_guide/azure-cyclecloud-cluster.md'
        - 'Install CMAQ on Cycle Cloud': 'user_guide/software-install-cyclecloud.md'
        - 'Install Input Data': 'user_guide/input-data-install.md'
        - 'Run CMAQ CONUS Benchmark on Cycle Cloud': 'user_guide/run-cmaq-benchmark-cyclecloud.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'Parallel Cluster Support': 'help/pcluster_support.md'
        - 'CMAQ Support': 'help/cmaq_support.md'
        - 'AWS Free Training': 'help/aws-free-training.md'
        - 'Key References on Cloud Computing': 'user_guide/key-references.md'
    - Future Work:
        - 'Future Work': 'user_guide/future_work.md'

theme:
  name: readthedocs
