site_name: cmaq_parallel_cluster
nav:
    - Home: 'index.md'
    - Quick Start Guide': 'quick-start.md'
    - 'User Guide':
        - 'Demo Cluster': 'user_guide/demo-cluster.md'
        - 'CMAQ Cluster': 'user_guide/cmaq-cluster.md'
        - 'QA CMAQ Output': 'user_guide/qa_cmaq_run.md'
        - 'Saving Output': 'user_guide/copy_output_to_S3_Bucket.md'
        - 'Elastic Network Adapter': 'user_guide/ena-cmaq-cluster.md'
        - 'Simultaneous Multithreading': 'user_guide/multithreading-cmaq-cluser.md'
        - 'Shared Lustre File System & Importing from S3 Bucket': 'user_guide/lustre-import-from-S3-bucket.md'
        - 'Shared EBS File System & Loading Sofware from Snapshot or AMI': 'user_guide/shared-ebs-load-snapshot.md'
        - 'System Requirements': 'user_guide/system-requirements.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
theme:
  name: readthedocs
