site_name: cmaq_parallel_cluster
nav:
    - Home: 'index.md'
    - User Guide for AWS Parallel Cluster:
        - 'System Requirements AWS Parallel Cluster': 'user_guide_pcluster/system-requirements-parallel-cluster.md'
        - AWS Parallel Cluster Configure, Create and Install Software & Data:
            - '1.1 Create Demo Cluster': 'user_guide_pcluster/demo-cluster.md'
            - '1.2 Create AWS MVP Parallel Cluster': 'user_guide_pcluster/aws-pcluster-cluster.md'
            - AWS Parallel Cluster Install Software and Data (two options)
            - Option 1:
                - '2.1 Install CMAQ Software on Pcluster': 'user_guide_pcluster/software-install-pcluster.md'
                - '2.2 Install Input Data': 'user_guide_pcluster/input-data-install_pcluster.md'
                - '2.3 Run CMAQ CONUS Benchmark on Pcluster': 'user_guide_pcluster/run-cmaq-benchmark-pcluster.md'
            - Option 2:  AWS Parallel Cluster Run from pre-loaded software and data (requires public permissions on snapshot or AMI):
                   - '3.1 Run CMAQ CONUS Benchmark from AMI/Snapshot and Imported S3 bucket on Lustre': 'user_guide_pcluster/lustre-import-from-S3-bucket.md'
        - AWS Parallel Cluster Post-Processing and QA:
            - '4.1 Compile and Run Post-processors': 'user_guide_pcluster/post-process-pcluster.md'
            - '4.2 Compare timings': 'user_guide_pcluster/parse_timing_pcluster.md'
            - '4.3 QA CMAQ Output': 'user_guide_pcluster/qa_cmaq_run_pcluster.md'
            - '4.4 Saving Output': 'user_guide_pcluster/copy_output_to_S3_Bucket.md'
    - User Guide for Azure Cycle Cloud:
        - 'System Requirements Azure': 'user_guide_cyclecloud/system-requirements-cyclecloud.md'
        - Azure CycleCloud Cluster Configure using Azure Web Interface:
             - '1.1 Azure CycleCloud Cluster': 'user_guide_cyclecloud/azure-cyclecloud-cluster.md'
        - CycleCloud Install Sofware and Data:    
             - Option 1:
             - '2.1 Install CMAQ on Cycle Cloud': 'user_guide_clyclecloud/software-install-cyclecloud.md'
             - '2.2 Install Input Data': 'user_guide_cyclecloud/input-data-install_cyclecloud.md'
             - '2.3 Run CMAQ CONUS Benchmark on Cycle Cloud': 'user_guide_cyclecloud/run-cmaq-benchmark-cyclecloud.md'
          - Option 2: (todo) 
             - '3.1 Run CMAQ CONUS Benchmark from pre-installed Azure volume': 'user_guide_cyclecloud/preinstall.md'
        - Azure CycleCloud Post-Processing and QA:
             - '4.1 Compile and Run Post-processors': 'user_guide_cyclecloud/post-process-cyclecloud.md'
             - '4.2 Compare timings': 'user_guide_cyclecloud/parse_timing_cyclecloud.md'
             - '4.3 QA CMAQ Output': 'user_guide_cyclecloud/qa_cmaq_run_cyclecloud.md'
             - '4.4 Saving Output': 'user_guide_cyclecloud/copy_output_to_archive_cyclecloud.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'Parallel Cluster Support': 'help/pcluster_support.md'
        - 'CMAQ Support': 'help/cmaq_support.md'
        - 'AWS Free Training': 'help/aws-free-training.md'
        - 'Key References on Cloud Computing': 'help/key-references.md'
    - Future Work:
        - 'Future Work': 'user_guide_pcluster/future_work.md'

theme:
  name: readthedocs
