site_name: cmaq_parallel_cluster
nav:
    - Home: 'index.md'
    - 'User Guide':
        - 'System Requirements AWS': 'user_guide/system-requirements-parallel-cluster.md'
        - 'System Requirements Azure': 'user_guide/system-requirements-cycle-cloud.md'
        - 'Demo Cluster': 'user_guide/demo-cluster.md'
        - 'AWS MVP Parallel Cluster': 'user_guide/aws-pcluster-cluster.md'
        - 'Azure CycleCloud Cluster': 'user_guide/azure-cyclecloud-cluster.md'
        - 'Install CMAQ on Pcluster': 'user_guide/software-install-pcluster.md'
        - 'Install CMAQ on Cycle Cloud': 'user_guide/software-install-cyclecloud.md'
        - 'Install Input Data': 'user_guide/input-data-install.md'
        - 'Run CMAQ CONUS Benchmark on Pcluster': 'user_guide/run-cmaq-benchmark-pcluster.md'
        - 'Run CMAQ CONUS Benchmark on Cycle Cloud': 'user_guide/run-cmaq-benchmark-cyclecloud.md'
        - 'Create AMI from Command Line': 'user_guide/create_ami_from_command_line.md'
        - 'CMAQ Cluster Software Loaded using AMI': 'user_guide/cmaq-cluster-from-ami.md'
        - 'CMAQ Cluster Software Loaded using Custom Bootstrap': 'user_guide/custom-bootstrap.md'
        - 'Run Combine and Post Processing': 'user_guide/post_combine.md'
        - 'Compare timings': 'user_guide/parse_timing.md'
        - 'QA CMAQ Output': 'user_guide/qa_cmaq_run.md'
        - 'Saving Output': 'user_guide/copy_output_to_S3_Bucket.md'
        - 'Parallel Cluster Update Policies': 'user_guide/update-policy.md'
        - 'Elastic Fabric Adapter': 'user_guide/ena-cmaq-cluster.md'
        - 'Simultaneous Multithreading': 'user_guide/multithreading-cmaq-cluser.md'
        - 'Shared Lustre File System & Importing from S3 Bucket': 'user_guide/lustre-import-from-S3-bucket.md'
        - 'Shared EBS File System & Loading Sofware from Snapshot or AMI': 'user_guide/shared-ebs-load-snapshot.md'
        - 'Slurm Multiple Queues': 'user_guide/slurm_multiple_queues.md'
        - 'Fault Tolerance Cluster': 'user_guide/fault_tolerance_cluster.md'
        - 'Virtual Private Cloud Management': 'user_guide/vpc_management.md'
        - 'pcluster3-config-converter': 'user_guide/pcluster3-config-converter.md'
        - 'Git Secrets': 'user_guide/git-secrets.md'
        - 'Tracking Costs': 'user_guide/cost-allocation-tags.md'
        - 'Future Work': 'user_guide/future_work.md'
        - 'Goal of Cluster Cloud Development': 'user_guide/goal.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'Parallel Cluster Support': 'help/pcluster_support.md'
        - 'CMAQ Support': 'help/cmaq_support.md'
        - 'AWS Free Training': 'help/aws-free-training.md'
        - 'Key References on Cloud Computing': 'user_guide/key-references.md'

theme:
  name: readthedocs
