site_name: cmaq_parallel_cluster
nav:
    - Home: 'index.md'
    - Quick Start Guide': 'quick-start.md'
    - 'User Guide':
        - 'System Requirements': 'user_guide/system-requirements.md'
        - 'Demo Cluster': 'user_guide/demo-cluster.md'
        - 'CMAQ Cluster': 'user_guide/cmaq-cluster.md'
        - 'Run Combine and Post Processing': 'user_guide/post_combine.md'
        - 'Compare timings': 'user_guide/parse_timing.md'
        - 'QA CMAQ Output': 'user_guide/qa_cmaq_run.md'
        - 'Saving Output': 'user_guide/copy_output_to_S3_Bucket.md'
        - 'Parallel Cluster Update Policies': 'user_guide/update-policy.md'
        - 'Elastic Network Adapter': 'user_guide/ena-cmaq-cluster.md'
        - 'Simultaneous Multithreading': 'user_guide/multithreading-cmaq-cluser.md'
        - 'Shared Lustre File System & Importing from S3 Bucket': 'user_guide/lustre-import-from-S3-bucket.md'
        - 'Shared EBS File System & Loading Sofware from Snapshot or AMI': 'user_guide/shared-ebs-load-snapshot.md'
        - 'Key References on Cloud Computing': 'user_guide/key-references.md'
        - 'AWS Free Training': 'user_guide/aws-free-training.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'Parallel Cluster Support': 'help/pcluster_support.md'
        - 'CMAQ Support': 'help/cmaq_support.md'

theme:
  name: readthedocs
