site_name: cmaq_pcluster
nav:
    - Home: 'index.md'
    - User Guide for AWS Parallel Cluster:
        - 'Description of MVP for Parallel Cluster': 'user_guide_pcluster/system-requirements-parallel-cluster.md'
        -  AWS Parallel Cluster Configure using AWS CLI 3.0 YAML file:
            - 'Create Demo Cluster': 'user_guide_pcluster/demo-cluster.md'
            - 'Create Parallel Cluster and upgrade compute node to c5n.18xlarge': 'user_guide_pcluster/aws-pcluster-cluster.md'
        - CMAQ Benchmark Option 1:
            - 'Run CMAQ CONUS Benchmark on cluster pre-loaded with software and input data': 'user_guide_pcluster/lustre-import-from-S3-bucket.md'
        - CMAQ Benchmark Option 2:
            - 'Install CMAQ Software on Pcluster': 'user_guide_pcluster/software-install-pcluster.md'
            - 'Install Input Data': 'user_guide_pcluster/input-data-install_pcluster.md'
            - 'Run CMAQ CONUS Benchmark on Pcluster': 'user_guide_pcluster/run-cmaq-benchmark-pcluster.md'
        - CMAQ Final Benchmark:
            - 'Run CMAQ CONUS Benchmark on HPC Cluster pre-loaded with softare and input data': `user_guide_pcluster/hpc6a-48xlarge_lustre.md` 
        - CMAQ CMAQ Virtual MAchine:
            - 'Run CMAQ v5.4 on Virtual Machine using 2018 12US1 Benchmark data: `user_guide_pcluster/cmaq-vm/preinstall.md'
        -  AWS Parallel Cluster Post-Processing and QA:
            - 'Compile and Run Post-processors': 'user_guide_pcluster/post-process-pcluster.md'
            - 'Compare timings': 'user_guide_pcluster/parse_timing_pcluster.md'
            - 'QA CMAQ Output': 'user_guide_pcluster/qa_cmaq_run_pcluster.md'
            - 'Saving Output': 'user_guide_pcluster/copy_output_to_S3_Bucket.md'
        - How to Create a Public Snapshot with preloaded software (used in CMAQ Benchmark Option 1) ': 'user_guide_pcluster/cmaq-cluster-load-software-snapshot.md' 
        -  Logout and Delete Parallel Cluster:
            - 'Logout and Delete Cluster': 'user_guide_pcluster/logout_delete_pcluster.md'
    - About:
        - 'License': 'license.md'
        - 'Release Notes': 'release-notes.md'
    - Help:
        - 'Parallel Cluster Support': 'user_guide_pcluster/help/pcluster_support.md'
        - 'CMAQ Support': 'user_guide_pcluster/help/cmaq_support.md'
        - 'AWS Free Training': 'user_guide_pcluster/help/aws-free-training.md'
        - 'Key References on Cloud Computing': 'user_guide_pcluster/help/key-references.md'
        - 'Frequently Asked Questions': 'user_guide_pcluster/help/faq.md'
    - Future Work:
        - 'Future Work': 'user_guide_pcluster/future_work.md'

theme:
  name: readthedocs
